services:
  app:
    build: .
    ports:
      - "5000:5000"

    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ORIO_DB
      - DB_USER=postgres
      - DB_PASSWORD=my_password
      - SECRET_KEY=ffggfghgjfghgfhfghfghfgh
      - UPLOAD_FOLDER=uploads
      - STATIC_IMG_FOLDER=static/img
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: ORIO_DB
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db